### ISSUE TITLE
What is the ReturnValue module?

### ISSUE THREAD

**Issue by davehodg** [briandfoy/cpan-critic#5]
$ cpanm --installdeps .
--> Working on .
Configuring /Users/daveh/workspace/cpan-critic ... OK
==> Found dependencies: ReturnValue
! Finding ReturnValue on cpanmetadb failed.
! Finding ReturnValue (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution ReturnValue
! Installing the dependencies failed: Module 'ReturnValue' is not installed
! Bailing out the installation for CPAN-Critic-0.001_001.

**Comment by briandfoy** [comment]
http://search.cpan.org/~bdfoy/ReturnValue-0.10_01/lib/ReturnValue.pm
